title: "Sara Tesfamariam"
email: "tes2sara@gmail.com"
tel: +47 94 48 22 03
LinkedIn: https://www.linkedin.com/in/sara-tesfamariam-b47417199/
GitHub: https://github.com/tes2sara
url: 'https://tes2sara.github.io/sara_tesfamariam/'
github_username: tes2sara

markdown: krandown
theme: minima


